### ISSUE TITLE
Production mode - console.debug is not a function

### ISSUE THREAD

**Issue by sveinng** [hgop/syllabus#8]
Þegar kerfið er keyrt upp í production mót kastar það eftirfarandi villu.

```
ttt-server | /opt/app/client/src/common/framework/incoming-socket-message-dispatcher.js:13
ttt-server |                 console.debug("Incoming message from socket.io: " + socketIoVerb + " message: ", message );
ttt-server |                         ^
ttt-server | 
ttt-server | TypeError: console.debug is not a function
ttt-server |     at Socket.listener (/opt/app/client/src/common/framework/incoming-socket-message-dispatcher.js:13:25)
ttt-server |     at emitOne (events.js:96:13)
ttt-server |     at Socket.emit (events.js:188:7)
ttt-server |     at /tmp/node_modules/socket.io/lib/socket.js:503:12
ttt-server |     at _combinedTickCallback (internal/process/next_tick.js:67:7)
ttt-server |     at process._tickCallback (internal/process/next_tick.js:98:9)
ttt-server | [nodemon] app crashed - waiting for file changes before starting...
```

console.debug virðist ekki hafa verið til í node.js í einhvern tíma. Í skránni server/globals.js er þessari loggun beint globally yfir í console.log þegar ekki er keyrt í production mode.

```
if(process.env.NODE_ENV!=='production'){
    global.console.debug = global.console.log;
}
```

Ég er ekki klár á því hvernig ég losa mig við þessa debug logga í produdction mode - tillögur vel þegnar. Svona geri ég þetta í dag.

```
if(process.env.NODE_ENV!=='production'){
    global.console.debug = global.console.log;
} else {
    // console.debug is not available in modern node.js 
    global.console.debug = global.console.log;
}
```

**Comment by stefaneg** [comment]
Það má  annaðhvort commenta út alla debug logga í kóðanum eða setja global.console.debug=function(){}, debug er þá "noop". Getur valið.
